import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import Cursor from "@/components/Cursor";
import Portfolio from "@/components/Portfolio";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { ScrollProvider } from "@/context/RefContext";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Dreamer portfolio",
  description: "Generated by DreamerWebdev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-slate-900 min-h-screen`}
        suppressHydrationWarning
        style={{
          backgroundImage: `url('/back.svg')`,
        }}
      >
        <ScrollProvider>
        <Navbar />
        <Cursor />
        <main className="grid xl:grid-cols-8 min-h-screen">
      {/* <div className="fixed inset-0 -inset -z-1 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/20 via-background to-background"></div> */}
          <Portfolio />
          <div
            role="main"
            className="xl:col-span-5 border-x  border-dashed border-slate-600"
          >
            {children}
          </div>
          <div className="hidden xl:sticky top-0 right-0 xl:col-span-1 h-screen xl:flex items-center justify-center">
            <Sidebar />
          </div>
        </main>
        </ScrollProvider>
      </body>
    </html>
  );
}
